apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-pedido
  labels:
    app: servico-pedido
spec:
  template:
    metadata:
      name: servico-pedido
      labels:
        app: servico-pedido
    spec:
      containers:
        - name: servico-pedido
          image: geter/pedido-techchallenge38:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_USER
              value: ${DB_USER}
            - name: DB_PASS
              value: ${DB_PASS}
            - name: TOPICO_PAGAMENTO_PENDENTE_ARN
              value: ${TOPICO_PAGAMENTO_PENDENTE_ARN}
            - name: TOPICO_PRODUCAO_ARN
              value: ${TOPICO_PRODUCAO_ARN}
            - name: FILA_PEDIDO_PRONTO
              value: ${FILA_PEDIDO_PRONTO}
            - name: FILA_PAGAMENTO_APROVADO
              value: ${FILA_PAGAMENTO_APROVADO}
            - name: FILA_PAGAMENTO_RECUSADO
              value: ${FILA_PAGAMENTO_RECUSADO}
            - name: FILA_PAGAMENTO_CANCELADO
              value: ${FILA_PAGAMENTO_CANCELADO}
            - name: GROUP_ID
              value: ${GROUP_ID}
            - name: ENV
              value: ${ENV}
          volumeMounts:
            - mountPath: /servico-pedido-volume
              name: servico-pedido-volume
      volumes:
        - name: servico-pedido-volume
          hostPath:
            path: /home/servico-pedido-volume
            type: DirectoryOrCreate
      serviceAccountName: pedido-serviceaccount
  replicas: 2
  selector:
    matchLabels:
      app: servico-pedido
