apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-pedido
  labels:
    app: servico-pedido
spec:
  template:
    metadata:
      name: servico-pedido
      labels:
        app: servico-pedido
    spec:
      containers:
        - name: servico-pedido
          image: geter/pedido-techchallenge38:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: ${DB_HOSTNAME}
            - name: DB_USER
              value: ${DB_USERNAME}
            - name: DB_PASS
              value: ${DB_PASSWORD}
          volumeMounts:
            - mountPath: /servico-pedido-volume
              name: servico-pedido-volume
      volumes:
        - name: servico-pedido-volume
          hostPath:
            path: /home/servico-pedido-volume
            type: DirectoryOrCreate
  replicas: 2
  selector:
    matchLabels:
      app: servico-pedido
