name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: eks-tech-challenge

jobs:
#  build:
#    uses: ./.github/workflows/reusable-workflow-build.yml
#
#  create_pull_request:
#    name: Create Pull Request to Develop
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#      repository-projects: write
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Get feature branch name
#        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV
#
#      - uses: ./.github/actions/create-pull-request
#        with:
#          source_branch: $FEATURE_BRANCH
#          target_branch: 'develop'
#          github_token: ${{ secrets.GITHUB_TOKEN }}

  #  TODO: alterar para executar depois do merge para main
  deploy:
#    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to EKS cluster
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Login to DockerHub
        run: docker login -u pedroprj -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t vwnunes/tech-challenge-61:latest .
          docker push vwnunes/tech-challenge-61

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment/lanchonete-deployment.yaml
          kubectl apply -f deployment/lanchonete-service.yaml
          kubectl apply -f deployment/alb-ingress.yaml
          kubectl get svc lanchonete-service
          echo "DB_HOST=$(echo ${{ secrets.DB_HOST }})" >> $GITHUB_ENV
          echo "DB_USER=$(echo ${{ secrets.DB_USER }})" >> $GITHUB_ENV
          echo "DB_PASS=$(echo ${{ secrets.DB_PASS }})" >> $GITHUB_ENV
