name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow-build.yml

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SonarQube
        run: docker-compose -f docker-compose-sonar.yml up -d

      - name: Wait for SonarQube to be ready
        run: |
          until curl -sSf "http://sonarqube:9000/api/system/status" >/dev/null; do
            echo "Waiting for SonarQube to be ready..."
            sleep 5
          done

      - name: Generate token
        run: |
          response=$(curl -sSf -X POST \
            -u admin:admin \
            "http://sonarqube:9000/api/user_tokens/generate" \
            -d "name=SONAR_TOKEN" \
            -d "type=GLOBAL_ANALYSIS_TOKEN")
          
          curl -sSf --request POST \
          --url 'http://sonarqube:9000/api/user_tokens/generate?SONAR_TOKEN=teste&type=GLOBAL_ANALYSIS_TOKEN' \
          --header 'Authorization: Basic YWRtaW46bm92YQ=='
          
          echo "SONAR_TOKEN=$(echo "$response" | jq -r '.token')" >> $GITHUB_ENV

      - name: Build and analyze with SonarQube
        run: mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.token=$SONAR_TOKEN

      - name: Check Test Coverage
        run: |
          COVERAGE=$(curl -s http://sonarqube:9000/api/qualitygates/project_status?projectKey=lanchonete | jq -r '.projectStatus.conditions[] | select(.metric == "coverage").status')
          if [[ "$COVERAGE" == "ERROR" ]]; then
            echo "Cobertura de teste abaixo de 80%."
            exit 1
          fi
        env:
          SONARQUBE_URL: 'http://sonarqube:9000'

      - name: Stop SonarQube
        run: docker-compose -f docker-compose-sonar.yml down

  create_pull_request:
    name: Create Pull Request to Develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get feature branch name
        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: $FEATURE_BRANCH
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}