name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow-build.yml

  tests:
    name: Unit Tests + Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          make test

  system-tests:
    name: System Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          make docker-build
          make docker-start
          make system-test
          make docker-stop

  create_pull_request:
    name: Create Pull Request to Develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs:
      - tests
      - system-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get feature branch name
        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: $FEATURE_BRANCH
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}