name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

env:
  SONARQUBE_URL: 'http://localhost:9000'
  PROJECT_KEY: 'lanchonete'

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow-build.yml

  tests:
    name: Unit Tests + Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: make test

  system-tests:
    name: System Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          make docker-build
          make docker-start
          make system-test
          make docker-stop

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs:
      - tests
      - system-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start SonarQube
        run: make docker-start-sonar

      - name: Wait for SonarQube to be ready
        run: |
          until curl -sSf "$SONARQUBE_URL/api/system/status" >/dev/null; do
            echo "Waiting for SonarQube to be ready..."
            sleep 10
          done
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Build and analyze with SonarQube
        run: make sonar-analysis SONARQUBE_URL=$SONARQUBE_URL
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Check Test Coverage
        run: |
          COVERAGE=$(curl -s $SONARQUBE_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY | jq -r '.projectStatus.conditions[] | select(.metric == "coverage").status')
          if [[ "$COVERAGE" == "ERROR" ]]; then
            echo "Cobertura de teste abaixo de 80%"
            exit 1
          fi
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Stop SonarQube
        run: make docker-stop-sonar

  create_pull_request:
    name: Create Pull Request to Develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: sonarqube-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get feature branch name
        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: $FEATURE_BRANCH
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}