name: SonarQube Analysis

on:
  pull_request:
    types: closed
    branches: develop

env:
  SONARQUBE_URL: 'http://localhost:9000'
  PROJECT_KEY: 'lanchonete'

jobs:
  sonarqube-analysis:
    if: github.event.pull_request.merged
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs:
      - tests
      - system-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start SonarQube
        run: make docker-start-sonar

      - name: Wait for SonarQube to be ready
        run: |
          until curl -sSf "$SONARQUBE_URL/api/system/status" >/dev/null; do
            echo "Waiting for SonarQube to be ready..."
            sleep 10
          done
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Build and analyze with SonarQube
        run: make sonar-analysis SONARQUBE_URL=$SONARQUBE_URL
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Check Test Coverage
        run: |
          COVERAGE=$(curl -s $SONARQUBE_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY | jq -r '.projectStatus.conditions[] | select(.metric == "coverage").status')
          if [[ "$COVERAGE" == "ERROR" ]]; then
            echo "Cobertura de teste abaixo de 80%"
            exit 1
          fi
        env:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}

      - name: Stop SonarQube
        run: make docker-stop-sonar
